### ISSUE TITLE
SteamVR Crash with SteamVR v1.10

### ISSUE THREAD

**Issue by Scipi** [matzman666/OpenVR-InputEmulator#185]
The new v1.10 update for SteamVR changes the steam menu layout and now having this installed causes SteamVR to crash whenever the home button is pressed

**Comment by Neprina** [comment]
Same Problem. Im sure its something they will have to fix on the files.

**Comment by SamThePie** [comment]
So i have the same issue, it actually took me hours to figure our what was the problem. 
Turns out, i had in the past installed SplitPixl's fix ''driver_vrinputemulator_release_hopefully.zip'' for one of the earlier issues in november 2018 where steam vr would always start in safe mode. if this is your case and you have this fix, try uninstalling and reinstalling inputemulator and it should fix it. or as least, it did fix it for me. i hope it helps. Cheers

**Comment by Markcreator** [comment]
> So i have the same issue, it actually took me hours to figure our what was the problem.
> Turns out, i had in the past installed SplitPixl's fix ''driver_vrinputemulator_release_hopefully.zip'' for one of the earlier issues in november 2018 where steam vr would always start in safe mode. if this is your case and you have this fix, try uninstalling and reinstalling inputemulator and it should fix it. or as least, it did fix it for me. i hope it helps. Cheers

This does not fix the issue for me. I have been experiencing this issue on the beta branch of SteamVR for a while now. Now that v1.10 is out, I am no longer able to use InputEmulator. I have reinstalled InputEmulator and SteamVR thoroughly many times.

The behavior I am seeing is that whenever I open the SteamVR overlay by pressing the home button on my Index controllers with InputEmulator installed, it freezes my headset, then turns off, and restarts SteamVR into safe mode. Any help would be appreciated!

EDIT: It seems like all the functionality of InputEmulator is actually fine, it is just the SteamVR overlay opening with InputEmulator installed that crashes SteamVR.

**Comment by SamThePie** [comment]
Weird... well let's see, I would assume you already did all of those but make sure your graphic drivers and windows is up to date.
I also reinstalled steamvr but it didnt change anything.
another thing i did is when i uninstalled inputemulator, i went in the steamvr folder, then drivers, and manually deleted the inputemulator folder.
if this also doesnt work, you could try installing this fix from 2018, i dont think it'll do anything useful in your case but its worth the try https://github.com/matzman666/OpenVR-InputEmulator/pull/130#issuecomment-442327528

**Comment by Markcreator** [comment]
I have tried all of those myself as well. Drivers and OS are up to date, manual uninstalls, and tried the fix. No dice.

I did some more testing and did some extensive digging through C:\Program Files (x86)\Steam\logs and C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\00vrinputemulator\bin\win64, but I have been unable to find a specific error exit code or exception documented within the logs.

I have a strong suspicion it might have to do with InputEmulator hooking into the new SteamVR overlay system incorrectly, though I don't have enough experience with the code to conclude anything. Is there anyone that could comment on this matter or has any other suggestions to backtrack this crash?

**Comment by Markcreator** [comment]
Update: tried to upgrade the InputEmulator source code to the latest version of OpenVR to see if that would help, but the OpenVR API has gone through a lot of changes over the last 2 years and I am not confident that I have the expertise to make all the changes required.

**Comment by Markcreator** [comment]
After some more testing I don't believe the issue lies within the overlay implementation. After spending some time disabling the dashboard overlay, the crash still occurs, leading me to believe the issue is actually in the driver itself.

**Comment by HellsPlumber** [comment]
Please try the following:
In SteamVR go to Settings > Camera > Disable Camera.

In my experience at least (using Valve Index), disabling the headset camera seems to have prevented SteamVR from crashing. Hopefully this can help someone debug the issue more thoroughly.

**Comment by Markcreator** [comment]
> Please try the following:
> In SteamVR go to Settings > Camera > Disable Camera.
> 
> In my experience at least (using Valve Index), disabling the headset camera seems to have prevented SteamVR from crashing. Hopefully this can help someone debug the issue more thoroughly.

Wow, this is a great find! This actually works for me. Disabling the camera seems to prevent the crash. That should be a good lead for someone more intimately familiar with the code to create a permanent fix.

**Comment by Repede** [comment]
> 
> 
> Please try the following:
> In SteamVR go to Settings > Camera > Disable Camera.
> 
> In my experience at least (using Valve Index), disabling the headset camera seems to have prevented SteamVR from crashing. Hopefully this can help someone debug the issue more thoroughly.

This has worked for me as well on a HTC Vive Headset and SteamVR 1.12.5 - Prior to that it would always crash with the emulator enabled.
